

spring:
  #  配置数据源
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://localhost:3306/order_system?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=CTT
    username: tangyiheng
    password: tyh1998217
#    username: root
#    password: 12345678


# 配置 mybatis-plus
mybatis-plus:
  configuration:
    # 配置 日志打印台输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      # 配置 逻辑删除
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:site/tyheng/wxorderapi/mapper/*.xml
server:
  port: 8081
